"""Versioned model-bundle registry and atomic active-version switching."""
from __future__ import annotations
import datetime as dt
import hashlib
import json
import os
import re
import shutil
from pathlib import Path
import config

BUNDLES_DIR = os.path.join(config.ARTIFACTS_DIR, "versions")
ACTIVE_POINTER = os.path.join(config.ARTIFACTS_DIR, "active.json")
REQUIRED_BUNDLE_FILES = (
    "isolation_forest.pkl",
    "feature_columns.json",
    "calibration.json",
    "metadata.json",
    "machine_calibrations.json",
    "machine_feature_normalizers.json",
)

OPTIONAL_BUNDLE_FILES = (
    "reference_timestamps.json",
    "reference_rows.json",
    "reference_features.csv",
    "validation_features.csv",
)

BUNDLE_FILES = REQUIRED_BUNDLE_FILES + OPTIONAL_BUNDLE_FILES
MODEL_LIFECYCLE_LOCK_ID = 724_913_208


def new_version_id(now: dt.datetime | None = None) -> str:
    now = now or dt.datetime.now(dt.timezone.utc)
    # Retraining is single-flight, but bootstrap registration and an operator
    # action can still land in the same second. Microseconds keep filesystem
    # bundle names and the database primary key collision-free without relying
    # on a retry after partial work has begun.
    return "v" + now.strftime("%Y-%m-%d-%H%M%S-%f")


def bundle_path(version_id: str) -> str:
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", version_id) or ".." in version_id:
        raise ValueError("Invalid model version identifier")
    return os.path.join(BUNDLES_DIR, version_id)


def reference_signature(reference_items) -> str:
    """Hash timestamp-only or machine-aware reference identities."""
    payload = "\n".join(sorted(str(x) for x in reference_items)).encode()
    return hashlib.sha256(payload).hexdigest()


def _bundle_reference_signature(directory: Path) -> str:
    rows_path = directory / "reference_rows.json"
    timestamps_path = directory / "reference_timestamps.json"
    if rows_path.is_file():
        rows = json.loads(rows_path.read_text(encoding="utf-8")) or []
        items = [f"{row['machine_id']}\0{row['timestamp']}" for row in rows]
    elif timestamps_path.is_file():
        items = json.loads(timestamps_path.read_text(encoding="utf-8")) or []
    else:
        items = []
    return reference_signature(items)


def normalize_display_name(value: str) -> str:
    name = " ".join(str(value).strip().split())
    if not 1 <= len(name) <= 80:
        raise ValueError("Model name must contain 1 to 80 characters")
    if any(ord(character) < 32 for character in name):
        raise ValueError("Model name cannot contain control characters")
    return name


def _clear_stale_pending_review_queue(cur, active_version_id: str) -> None:
    """Hide unresolved review candidates produced by superseded models.

    Prediction history remains immutable. Confirmed reviews also remain intact;
    only pending queue markers are cleared so new review work is generated by
    the newly active model.
    """
    cur.execute(
        """UPDATE spindle_predictions
           SET alert_status=NULL,
               alert_reviewed_by=NULL,
               alert_reviewed_at=NULL
           WHERE model_version<>%s AND alert_status='pending'""",
        (active_version_id,),
    )
    cur.execute(
        """UPDATE spindle_predictions
           SET near_miss_status=NULL,
               near_miss_reviewed_by=NULL,
               near_miss_reviewed_at=NULL
           WHERE model_version<>%s AND near_miss_status='pending'""",
        (active_version_id,),
    )


def commissioned_machines(version_id: str) -> set[str]:
    """Return machines covered by both required machine-specific artifacts."""
    try:
        directory = _validated_bundle(version_id)
        calibrations = json.loads(
            (directory / "machine_calibrations.json").read_text(encoding="utf-8")
        )
        normalizers = json.loads(
            (directory / "machine_feature_normalizers.json").read_text(encoding="utf-8")
        )
    except (FileNotFoundError, OSError, TypeError, ValueError, json.JSONDecodeError):
        return set()
    return {str(machine_id) for machine_id in calibrations}.intersection(
        str(machine_id) for machine_id in normalizers
    )


def snapshot_current(version_id: str) -> str:
    target = Path(bundle_path(version_id))
    target.mkdir(parents=True, exist_ok=False)
    try:
        for name in BUNDLE_FILES:
            src = Path(config.ARTIFACTS_DIR) / name
            if src.exists():
                shutil.copy2(src, target / name)
        meta = target / "metadata.json"
        if meta.exists():
            data = json.loads(meta.read_text())
            data["version_id"] = version_id
            meta.write_text(json.dumps(data, indent=2))
    except Exception:
        shutil.rmtree(target, ignore_errors=True)
        raise
    return str(target)


def clear_root_staging() -> None:
    """Remove a manual-training staging bundle after it is versioned safely."""
    root = Path(config.ARTIFACTS_DIR)
    for name in BUNDLE_FILES:
        path = root / name
        if path.is_file():
            path.unlink()


def _validated_bundle(version_id: str) -> Path:
    src_dir = Path(bundle_path(version_id))
    if not src_dir.exists():
        raise FileNotFoundError(f"Missing bundle {src_dir}")
    required = REQUIRED_BUNDLE_FILES
    missing = [name for name in required if not (src_dir / name).exists()]
    if missing:
        raise ValueError(f"Bundle {version_id} missing required files: {missing}")
    return src_dir.resolve()


def activate_bundle(version_id: str) -> None:
    """Atomically select one immutable version directory without copying it."""
    _validated_bundle(version_id)
    artifacts_root = Path(config.ARTIFACTS_DIR)
    artifacts_root.mkdir(parents=True, exist_ok=True)
    payload = {
        "version_id": version_id,
        "bundle_dir": (Path("versions") / version_id).as_posix(),
    }
    temporary = artifacts_root / f".active-{os.getpid()}.tmp"
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, ACTIVE_POINTER)


def active_bundle_path(required: bool = True) -> Path | None:
    pointer = Path(ACTIVE_POINTER)
    if not pointer.is_file():
        if required:
            raise FileNotFoundError(
                f"No active model pointer exists at {pointer}. Register or promote a model first."
            )
        return None
    try:
        payload = json.loads(pointer.read_text(encoding="utf-8"))
        version_id = str(payload["version_id"])
        stored_dir = str(payload["bundle_dir"])
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Invalid active model pointer {pointer}: {exc}") from exc
    expected = _validated_bundle(version_id)
    expected_relative = (Path("versions") / version_id).as_posix()
    if stored_dir != expected_relative:
        raise ValueError(
            f"Active model pointer must use bundle_dir {expected_relative!r}, got {stored_dir!r}"
        )
    selected = (Path(config.ARTIFACTS_DIR) / stored_dir).resolve()
    if selected != expected:
        raise ValueError(
            f"Active model pointer path does not match version {version_id!r}: {stored_dir!r}"
        )
    return expected


def active_version() -> str | None:
    """Return the version selected by the filesystem pointer."""
    pointer = Path(ACTIVE_POINTER)
    if not pointer.is_file():
        return None
    try:
        active_bundle_path(required=True)
        payload = json.loads(pointer.read_text(encoding="utf-8"))
        return str(payload["version_id"])
    except (OSError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Invalid active model pointer {pointer}: {exc}") from exc


def restore_active_version(version_id: str | None) -> None:
    """Restore a previous pointer after a surrounding transaction fails."""
    if version_id:
        activate_bundle(version_id)
    else:
        Path(ACTIVE_POINTER).unlink(missing_ok=True)


def register_initial_bundle(
    conn,
    version_id: str,
    validation_report: dict,
    display_name: str | None = None,
    promoted_by: str = "initial-training-cli",
) -> dict:
    """Register one directly-written commissioning bundle.

    The complete bundle becomes active atomically. Commissioning scores remain
    attached as advisory evidence and do not block activation.
    """
    directory = _validated_bundle(version_id)
    report = dict(validation_report or {})
    # Commissioning validation is evidence, not an activation lock. A fully
    # written model is registered; operators can inspect its score in the UI.
    accepted = True
    name = normalize_display_name(display_name or f"Initial model {version_id[1:11]}")
    signature = _bundle_reference_signature(directory)
    previous_version = active_version()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT pg_advisory_xact_lock(%s)", (MODEL_LIFECYCLE_LOCK_ID,))
            cur.execute("SELECT 1 FROM model_versions WHERE version_id=%s", (version_id,))
            if cur.fetchone():
                raise ValueError(f"Model version already exists: {version_id}")
        if accepted:
            activate_bundle(version_id)
        with conn.cursor() as cur:
            if accepted:
                cur.execute(
                    "UPDATE model_versions SET status='retired' WHERE status='active'"
                )
            cur.execute(
                """INSERT INTO model_versions
                     (version_id,display_name,artifact_path,reference_signature,status,
                      validation_report,promoted_at,promoted_by)
                   VALUES(%s,%s,%s,%s,%s,%s::jsonb,
                          CASE WHEN %s THEN now() ELSE NULL END,
                          CASE WHEN %s THEN %s ELSE NULL END)""",
                (
                    version_id,
                    name,
                    str(directory),
                    signature,
                    "active" if accepted else "rejected",
                    json.dumps(report),
                    accepted,
                    accepted,
                    promoted_by,
                ),
            )
            if accepted:
                _clear_stale_pending_review_queue(cur, version_id)
                cur.execute("NOTIFY model_changed, %s", (version_id,))
        conn.commit()
    except Exception:
        conn.rollback()
        if accepted:
            try:
                restore_active_version(previous_version)
            except Exception:
                pass
        raise
    return {
        "version_id": version_id,
        "display_name": name,
        "status": "active" if accepted else "rejected",
        "artifact_path": str(directory),
    }


def rename_version(conn, version_id: str, display_name: str) -> str:
    """Rename only the operator-facing label; immutable IDs/paths stay stable."""
    name = normalize_display_name(display_name)
    with conn.cursor() as cur:
        cur.execute(
            "UPDATE model_versions SET display_name=%s WHERE version_id=%s",
            (name, version_id),
        )
        if cur.rowcount != 1:
            conn.rollback()
            raise ValueError(f"Unknown model version: {version_id}")
    conn.commit()
    return name


def promote(conn, version_id: str, promoted_by: str) -> None:
    with conn.cursor() as cur:
        # Serialize the database decision and filesystem pointer switch across
        # every API process. Row locks alone do not protect two different
        # version rows from being promoted at the same time.
        cur.execute("SELECT pg_advisory_xact_lock(%s)", (MODEL_LIFECYCLE_LOCK_ID,))
        cur.execute(
            "SELECT status FROM model_versions WHERE version_id=%s FOR UPDATE",
            (version_id,),
        )
        target = cur.fetchone()
        if not target or target[0] not in ("shadow", "retired", "active", "rejected"):
            raise ValueError(f"Unknown model version: {version_id}")
        if target[0] == "shadow" and not (Path(bundle_path(version_id)) / "validation_features.csv").is_file():
            raise ValueError(
                f"Shadow model {version_id} is missing its independent validation_features.csv artifact"
            )
        previous_version = active_version()

    # The filesystem pointer is the authoritative runtime selector. Database
    # status remains a registry/audit mirror for the website.
    try:
        activate_bundle(version_id)
        with conn.cursor() as cur:
            cur.execute("UPDATE model_versions SET status='retired' WHERE status='active' AND version_id<>%s", (version_id,))
            cur.execute("""UPDATE model_versions SET status='active', promoted_at=now(), promoted_by=%s
                           WHERE version_id=%s AND status IN ('shadow','retired','active','rejected')""", (promoted_by, version_id))
            if cur.rowcount != 1:
                raise ValueError(f"Model version became unavailable during promotion: {version_id}")
            cur.execute(
                """UPDATE spindle_predictions
                   SET added_to_reference_at=now(),candidate_model_version=NULL
                   WHERE candidate_model_version=%s
                     AND reference_candidate_at IS NOT NULL
                     AND added_to_reference_at IS NULL""",
                (version_id,),
            )
            _clear_stale_pending_review_queue(cur, version_id)
            cur.execute("NOTIFY model_changed, %s", (version_id,))
        conn.commit()
    except Exception:
        conn.rollback()
        try:
            restore_active_version(previous_version)
        except Exception:
            pass
        raise


def delete_version(conn, version_id: str) -> None:
    """
    Delete a non-active registry row and its immutable artifact directory.
    Staged prediction candidates are released by their foreign key. The active
    model can never be deleted here — promote a different version first —
    because it is the model currently serving predictions.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT pg_advisory_xact_lock(%s)", (MODEL_LIFECYCLE_LOCK_ID,))
        cur.execute("SELECT status, artifact_path FROM model_versions WHERE version_id=%s FOR UPDATE", (version_id,))
        row = cur.fetchone()
        if not row:
            raise ValueError(f"Unknown model version: {version_id}")
        status, artifact_path = row
        if status == "active" or active_version() == version_id:
            raise ValueError("Cannot delete the active model version — promote a different version first.")
        resolved_artifact = Path(artifact_path).resolve() if artifact_path else None
        bundles_root = Path(BUNDLES_DIR).resolve()
        if resolved_artifact and (resolved_artifact == bundles_root or not resolved_artifact.is_relative_to(bundles_root)):
            raise ValueError(f"Refusing to delete model artifacts outside the version registry: {artifact_path}")
        cur.execute(
            """SELECT count(*) FROM simulation_runs
               WHERE model_version=%s AND status<>'draft'""",
            (version_id,),
        )
        simulation_count = int(cur.fetchone()[0])
        if simulation_count:
            raise ValueError(
                f"Cannot delete model {version_id}: {simulation_count} saved simulation "
                "run(s) are pinned to it. Delete those runs first."
            )
        cur.execute("DELETE FROM model_versions WHERE version_id=%s", (version_id,))
    conn.commit()
    if resolved_artifact and resolved_artifact.is_dir():
        shutil.rmtree(resolved_artifact, ignore_errors=True)
